INSERT INTO USER
(EMAIL, NAME, PASSWORD, USERNAME)
VALUES('amperca@ph.ibm.com', 'Charles Austria Amper', '$2a$10$kxP2K0386Vf6A8gMZTt0zO7lbUr.B.cHgij7J2DVgY7MzHyxLhtRy', 'amperca');

INSERT INTO USER
(EMAIL, NAME, PASSWORD, USERNAME)
VALUES('admin@admin.com', 'admin', '$2a$10$PF0MXp1Ui/.yINrsXyhhdOcb1ghFl0YK1FayleCwPVMkPNSu2NTfy', 'admin');

INSERT INTO ROLE
(NAME)
VALUES('USER');

INSERT INTO ROLE
(NAME)
VALUES('ADMIN');


INSERT INTO USER_ROLE
(USER_ID, ROLE_ID)
VALUES(1, 1);
INSERT INTO USER_ROLE
(USER_ID, ROLE_ID)
VALUES(2, 1);
INSERT INTO USER_ROLE
(USER_ID, ROLE_ID)
VALUES(2, 2);
